In [78]:
import torch
x = torch.rand(5, 3)
print(x)


tensor([[0.9879, 0.2197, 0.0764],
        [0.7571, 0.6854, 0.4101],
        [0.6359, 0.3017, 0.8449],
        [0.7741, 0.7480, 0.5759],
        [0.5645, 0.5294, 0.0702]])


In [79]:
X = torch.tensor([[1, 4, 3],[3, 2, 0]])
X

tensor([[1, 4, 3],
        [3, 2, 0]])

In [80]:
X.shape

torch.Size([2, 3])

In [81]:
X.dtype

torch.int64

In [82]:
X[:,1:2]

tensor([[4],
        [2]])

In [83]:
X + 1

tensor([[2, 5, 4],
        [4, 3, 1]])

In [84]:
X * 2

tensor([[2, 8, 6],
        [6, 4, 0]])

In [85]:
X.T

tensor([[1, 3],
        [4, 2],
        [3, 0]])

In [86]:
X.max()

tensor(4)

In [87]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,3,4])

In [88]:
a @ b

tensor(22)

In [89]:
a * b

tensor([ 4,  6, 12])

In [90]:
import numpy as np
c = torch.FloatTensor(np.array((2,3,4)))
c.dtype

torch.float32

In [91]:
c = torch.tensor(np.array((2.2,3.1,4.3)), dtype= torch.float32)
c.dtype

torch.float32

In [92]:
X = torch.tensor([1.2, -1.3, 3.23])

In [93]:
X.dtype

torch.float32

In [94]:
X.relu()

tensor([1.2000, 0.0000, 3.2300])

In [95]:
X

tensor([ 1.2000, -1.3000,  3.2300])

In [96]:
X.relu_() # in-place operation

tensor([1.2000, 0.0000, 3.2300])

In [97]:
X

tensor([1.2000, 0.0000, 3.2300])

In [98]:
X.device

device(type='cpu')

In [126]:
x = torch.tensor(3.0, requires_grad=True)

In [127]:
f = x ** 2

In [128]:
f

tensor(9., grad_fn=<PowBackward0>)

In [129]:
f.backward()

In [130]:
x.grad

tensor(6.)

In [133]:
learning_rate = 0.1
with torch.no_grad():
    x -= learning_rate * x.grad 

In [134]:
x

tensor(1.8000, requires_grad=True)