In [30]:
import torch 

In [31]:
X = torch.tensor([1.2, -3.2, 2.6])

In [32]:
X

tensor([ 1.2000, -3.2000,  2.6000])

In [33]:
X.relu()

tensor([1.2000, 0.0000, 2.6000])

In [34]:
X

tensor([ 1.2000, -3.2000,  2.6000])

In [35]:
X.device

device(type='cpu')

In [36]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

In [37]:
X = X.to(device)

In [38]:
X.device

device(type='cuda', index=0)

In [39]:
y = torch.tensor([2.3, -2.4, 6,3])

In [40]:
y.device

device(type='cpu')

In [41]:
y = y.to("cuda")

In [42]:
y.device

device(type='cuda', index=0)

In [43]:
z = torch.tensor([2, 4, 5,], device="cuda")

In [44]:
z.device

device(type='cuda', index=0)

In [45]:
M = torch.rand((1000, 1000))

In [46]:
%timeit M @ M

17.6 ms ± 3.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [47]:
M = M.to(device)

In [49]:
%timeit M @ M

687 µs ± 8.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
